project:
  type: website
  output-dir: docs
  post-render:
    - "cp -r posts/class-imbalance-healthcare/_presentation_files docs/posts/class-imbalance-healthcare/"
    - "cp -r posts/class-imbalance-healthcare/img docs/posts/class-imbalance-healthcare/"

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "myblog"
  navbar:
    right:
      - about.qmd
      - icon: backpack
        href: https://jacksonlu.ca/
      - icon: github
        href: https://github.com/jluover9000
      - icon: linkedin
        href: https://www.linkedin.com/in/jackson-lu-profiles/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



